- alias: Lights - Turn Off Garage Light After Midnight

  trigger:
    - platform: time
      at: '20:45:00'

  action:
    - service: light.turn_off
      data:
        entity_id: light.family_room_main_lights