- alias: Lights - Turn On Lights in basement

  trigger:
    - platform: time
      at: '19:45:00'

  action:
    - service: light.turn_on
      data:
        entity_id: light.family_room_main_lights

- alias: Lights - Turn Off Lights in basement

  trigger:
    - platform: time
      at: '21:45:00'

  action:
    - service: light.turn_off
      data:
        entity_id: light.family_room_main_lights