---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/Denver
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named integrations
  customize: !include_dir_merge_named ./customizations/entities

discovery:
  ignore:
    - homekit
    - igd

lutron_caseta_pro:
  bridges:
    - host: !secret lutron_caseta_pro_bridges_host
      mac: !secret lutron_caseta_pro_bridges_mac

pi_hole:
  host: !secret pi_hole_host
  ssl: false
  verify_ssl: false

automation: !include automations.yaml
automation split: !include_dir_list automations

shell_command:
  roku_on: "curl -X POST {{ roku_host }}/keypress/home"
  roku_youtube_phish: "curl -X POST {{ roku_host}}/launch/837?contentId=8BN_Tyl8c00&mediaType=live"

script:
  roku_phish_youtube_on:
    alias: "Turn on Phish Youtube"
    sequence:
      - service: shell_command.roku_on
        data_template:
          roku_host: !secret roku_host
      - delay:
          seconds: 2
      - service: shell_command.roku_youtube_phish
        data_template:
          roku_host: !secret roku_host
  test_notification:
    alias: "Test notification"
    sequence:
      - service: notify.mobile_app_et
        data:
          title: "Test notification"
          message: "This is a test"
          data:
            push:
              badge: 25

scene: !include_dir_merge_list scenes
sensor: !include sensors.yaml

frontend:
  themes: !include_dir_merge_named themes

device_tracker:
  - platform: tile
    username: !secret tile_username
    password: !secret tile_password