---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/Denver
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named integrations

discovery:
  ignore:
    - homekit
    - igd

lutron_caseta_pro:
  bridges:
    - host: !secret lutron_caseta_pro_bridges_host
      mac: !secret lutron_caseta_pro_bridges_mac

pi_hole:
  host: !secret pi_hole_host
  ssl: false
  verify_ssl: false

group: !include_dir_merge_named group
automation: !include_dir_merge_list automations
# automation:
#   - alias: 'Send Notification'
#     trigger:
#     action:
#       service: notify.et
#       message: 'Notification text'


shell_command:
  roku_on: "curl -X POST {{ roku_host }}/keypress/home"
  roku_youtube_phish: "curl -X POST {{ roku_host}}/launch/837?contentId=8BN_Tyl8c00&mediaType=live"

script:
  roku_phish_youtube_on:
    alias: "Turn on Phish Youtube"
    sequence:
      - service: shell_command.roku_on
        data_template:
          roku_host: !secret roku_host
      - delay:
          seconds: 2
      - service: shell_command.roku_youtube_phish
        data_template:
          roku_host: !secret roku_host

scene: !include_dir_merge_list scenes
sensor: !include sensors.yaml

frontend:
  themes: !include_dir_merge_named themes
