---
# Turn lights on when door contact sensor is on
#
alias: Turn laundry lights on when someone enters
trigger:
  - platform: state
    entity_id: binary_sensor.ecolink_door_window_sensor_sensor
    from: 'off'
    to: 'on'
action:
  - service: light.turn_on
    entity_id:  light.laundry_room_main_lights