---
#
#
alias: 'Send notification if the garage is open'
trigger:
  platform: state
  entity_id: 'cover.linear_nortek_security_control_llc_gd00z_4_garage_door_opener_remote_controller_barrier_state_label'
condition:
  - condition: time
    after: '20:00:00'
    before: '06:00:00'
  - condition: state
    entity_id: 'cover.linear_nortek_security_control_llc_gd00z_4_garage_door_opener_remote_controller_barrier_state_label'
    state: 'open'
action:
  - service: notify.mobile_app_et
    data:
      title: "Garage door open!"
      message: "Close it please :)"
      data:
        push:
          badge: 25